services:

  postgres13:
    image: postgres:13.21
    container_name: postgres13
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PG13_PASSWORD}
      POSTGRES_DB: testpostgres
    ports:
      - "5433:5432"
    volumes:
      - pg13_data:/var/lib/postgresql/data

  mysql8:
    image: mysql:8.4
    container_name: mysql8
    restart: unless-stopped
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: testmysql
     MYSQL_USER: admin
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql8_data:/var/lib/mysql

volumes:
  pg13_data:
  mysql8_data:
